#write a py prog to display all airthmetic operators
a = int(input("Enter 1st number:"))
b = int(input("Enter 2nd number:"))
print("Your Sum of "+str(a)+" and "+str(b)+" is",a+b)
print("Your Subtraction of "+str(a)+" and "+str(b)+" is",a-b)
print("Your Division of "+str(a)+" and "+str(b)+" is",a/b)
print("Your Multiplication of "+str(a)+" and "+str(b)+" is",a*b)
print("Your Power of "+str(a)+" and "+str(b)+" is",a**b)
print("Your F Division of "+str(a)+" and "+str(b)+" is",a//b)
print("Your Modulo of "+str(a)+" and "+str(b)+" is",a%b)